make-dist should stop on errors

diff --git a/make-dist b/make-dist
--- a/make-dist
+++ b/make-dist
@@ -1,6 +1,13 @@
 #!/bin/sh
 
 THOME=${THOME:-/packages/localsrc/Tribblix}
+DESTDIR=/export/tribblix/dist
+
+case $# in
+    1)
+	DESTDIR="${DESTDIR}.$1"
+	;;
+esac
 
 TDIR=${THOME}/tribblix-build
 case `uname -p` in
@@ -16,6 +23,11 @@ i386)
 	;;
 esac
 
+if [ ! -d ${DESTDIR}/usr/bin/ls ]; then
+    echo "ERROR: Package install failed!"
+    exit 1
+fi
+
 case `uname -p` in
 sparc)
 	$TDIR/mk-pkgs-zap.sparc $*
@@ -24,5 +36,10 @@ i386)
 	$TDIR/mk-pkgs-zap $*
 	;;
 esac
+
+if [ ! -d ${DESTDIR}/pkgs/catalog ]; then
+    echo "ERROR: Extra packages failed!"
+    exit 1
+fi
 
 $TDIR/build_iso $*
diff --git a/make-lx-dist b/make-lx-dist
--- a/make-lx-dist
+++ b/make-lx-dist
@@ -1,6 +1,13 @@
 #!/bin/sh
 
 THOME=${THOME:-/packages/localsrc/Tribblix}
+DESTDIR=/export/tribblix/dist
+
+case $# in
+    1)
+	DESTDIR="${DESTDIR}.$1"
+	;;
+esac
 
 TDIR=${THOME}/tribblix-build
 case `uname -p` in
@@ -13,10 +20,20 @@ i386)
 	;;
 esac
 
+if [ ! -d ${DESTDIR}/usr/bin/ls ]; then
+    echo "ERROR: Package install failed!"
+    exit 1
+fi
+
 case `uname -p` in
 i386)
 	$TDIR/mk-lx-pkgs-zap $*
 	;;
 esac
+
+if [ ! -d ${DESTDIR}/pkgs/catalog ]; then
+    echo "ERROR: Extra packages failed!"
+    exit 1
+fi
 
 $TDIR/lx_iso $*
