make-dist needs to exit early when install-pkgs fails

diff --git a/make-dist b/make-dist
--- a/make-dist
+++ b/make-dist
@@ -81,9 +81,17 @@ TDIR=${THOME}/tribblix-build
 case $(uname -p) in
 sparc)
 	"$TDIR/install-pkgs.sparc" -D "${DESTTOP}" $NFLAG -O "${OVBASE}" -R "${RELEASE}" "$@"
+	if [ $? -ne 0 ]; then
+	    echo "ERROR: pkg install failed"
+	    exit 1
+	fi
 	;;
 i386)
 	"$TDIR/install-pkgs" -D "${DESTTOP}" $NFLAG -O "${OVBASE}" -R "${RELEASE}" "$@"
+	if [ $? -ne 0 ]; then
+	    echo "ERROR: pkg install failed"
+	    exit 1
+	fi
 	;;
 *)
 	echo "ERROR: unrecognized architecture"
diff --git a/make-lx-dist b/make-lx-dist
--- a/make-lx-dist
+++ b/make-lx-dist
@@ -84,6 +84,10 @@ TDIR=${THOME}/tribblix-build
 case $(uname -p) in
 i386)
 	"$TDIR/install-lx-pkgs" -D "${DESTTOP}" $NFLAG -O "${OVBASE}" -R "${RELEASE}" "$@"
+	if [ $? -ne 0 ]; then
+	    echo "ERROR: pkg install failed"
+	    exit 1
+	fi
 	;;
 *)
 	echo "ERROR: unrecognized architecture for LX"
