make-dist release validity check

diff --git a/make-dist b/make-dist
--- a/make-dist
+++ b/make-dist
@@ -38,6 +38,13 @@ while getopts "D:NO:QR:" opt; do
 done
 shift $((OPTIND-1))
 
+case $RELEASE in
+    *lx*)
+	echo "ERROR: use make-lx-dist for omnitribblix."
+	exit 1
+	;;
+esac
+
 case $# in
     1)
 	DESTDIR="${DESTDIR}.$1"
