Stronger checking that we're given a valid release

diff --git a/mk-pkgs-zap b/mk-pkgs-zap
--- a/mk-pkgs-zap
+++ b/mk-pkgs-zap
@@ -49,6 +49,14 @@ TPKGDIR=${THOME}/pkgs
 IPKGDIR=${THOME}/illumos-pkgs-m${RELEASE}/pkgs
 
 #
+# check we have illumos packages, and a catalog
+#
+if [ ! -f ${IPKGDIR}/catalog ]; then
+    echo "ERROR: no illumos packages (or catalog) for release $RELEASE"
+    exit 1
+fi
+
+#
 # the one argument is a variant, which sets the destination directory
 #
 # if there's a variant overlays.iso, then use that
